# fly.toml app configuration file generated for icard-django-loubvg-ancient-river-7412 on 2024-12-09T23:33:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'icard-django-loubvg-ancient-river-7412'
primary_region = 'scl'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'
  FRONTEND_ORIGIN_URL="https://icard-react-434iobokl-cljmunoz-gmailcoms-projects.vercel.app"
  BACKEND_ORIGIN_URL="https://icard-django-loubvg-ancient-river-7412.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
